version: '3.8'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-app
    environment:
      - MONGO_URL=$MONGO_URL
    container_name: node-app
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    volumes:
      - .:/app
    networks:
      - app-network

  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:5.0-ubuntu2004
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: '27017'
      ME_CONFIG_MONGODB_URL: 'mongodb://mongodb:27017'
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - type: bind
        source: ./wait-for.sh
        target: /wait-for.sh
    entrypoint:
      - /bin/sh
      - /wait-for.sh
      - mongodb:27017
      - --
      - tini
      - --
      - /docker-entrypoint.sh

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
